# Generated by Django 4.2.5 on 2023-11-05 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('AV', 'Active'), ('DE', 'Deactivated')], default='AV', max_length=2)),
                ('subscription_id', models.CharField(default=None, max_length=100, null=True)),
                ('files_used', models.IntegerField(default=0)),
                ('queries_used', models.IntegerField(default=0)),
                ('max_files', models.IntegerField()),
                ('max_queries', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
