# Generated by Django 4.2.5 on 2023-11-05 17:54

from django.db import migrations, models
import uploads_app.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=63)),
                ('docfile', models.FileField(upload_to=uploads_app.utils.create_path)),
            ],
        ),
    ]
